apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    kubernetes.io/name: "redis"
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: default
    port: 6379 
    nodePort: 32379

